version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elk         
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "19200:9200"
      - "19300:9300"
    # environment:
    #   ES_JAVA_OPTS: "-Xmx256m -Xms256m"
     # ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
   #   discovery.type: single-node
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: "zen"
      discovery.zen.ping.unicast.hosts: "elasticsearch2,elasticsearch3"      
    # networks:
    #   - elk
  elasticsearch2:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elk2       
    environment:
      node.name: elasticsearch2
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: "zen"
      node.attr.zone: cold       
      discovery.zen.ping.unicast.hosts: "elasticsearch,elasticsearch3"

  elasticsearch3:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elk3    
    environment:
      node.name: elasticsearch3
      node.attr.zone: warm      
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: "zen"
      discovery.zen.ping.unicast.hosts: "elasticsearch,elasticsearch2"
  # logstash:
  #   build:
  #     context: logstash/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - type: bind
  #       source: ./logstash/config/logstash.yml
  #       target: /usr/share/logstash/config/logstash.yml
  #       read_only: true
  #     - type: bind
  #       source: ./logstash/pipeline
  #       target: /usr/share/logstash/pipeline
  #       read_only: true
  #   ports:
  #     - "5044:5044"
  #     - "5000:5000/tcp"
  #     - "5000:5000/udp"
  #     - "9600:9600"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "15601:5601"
    # networks:
    #   - elk
    depends_on:
      - elasticsearch

# networks:
#   elk:
#     driver: bridge

volumes:
  elasticsearch:
